{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cost-analytics.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          # Frontend Path
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "cost-analytics.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontend.service.port }}
          # Backend API Path (If applicable)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "cost-analytics.fullname" . }}-backend
                port:
                  number: {{ .Values.backend.service.port }}
  {{- end }}
